import React from 'react';
import './GeminiNews.css';
import { FaRegNewspaper } from "react-icons/fa6";

const GeminiNews = () => {
  return (
    <div className="gemini-container">
      <div className="gemini-left">
        <FaRegNewspaper className="gemini-icon" />
        <h2>The week&apos;s top headlines, selected by Gemini</h2>
        <p>
          Google&apos;s pushing AI forward. New TPUs power proactive AI via
          &quot;inference,&quot; matching patterns to predict needs. Gemini CLI brings
          AI to developers&apos; terminals, offering coding help and task automation.
          Chromebook Plus boasts enhanced AI, like smart tab grouping and image editing.
          Search Live lets you have voice conversations with Search, exploring web links
          hands-free. Try Gemini CLI and explore Chromebook Plus for AI tools.
        </p>
        <p className="gemini-f " style={{fontSize:"14px"}}>This content is generated by Google AI. Generative AI is experimental.</p>
      </div>
      <div className="gemini-right">
        <ul>
          <li>Ask a Techspert: What is inference?</li>
          <li>Gemini CLI: your open-source AI agent</li>
          <li>Our most advanced Chromebook Plus yet, and new helpful AI features</li>
          <li>Search Live: Talk, listen and explore in real time with AI Mode</li>
        </ul>
      </div>
    </div>
  );
};

export default GeminiNews;
